// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbtkjvgruhvzzdeyobwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1idGtqdmdydWh2enpkZXlvYndjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDY5NTIsImV4cCI6MjA3MTIyMjk1Mn0.XGsZEl8nyODQF54t6kPmEn3KnIf9xn3XiINPZS_R3Kg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});